name: Deploy instagram-mern backend

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t trituong/insta-backend .
      - name: Publish Image to docker hub
        run: docker push trituong/insta-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Change Docker socket permission
        run: sudo chmod 666 /var/run/docker.sock
      - name: Pull Image from docker hub
        run: docker pull trituong/insta-backend:latest
      - name: Delete old container
        run: docker rm -f insta-be-container
      - name: Run docker container
        run: docker run -d -p 4000:4000 --network insta-net --name insta-be-container -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} trituong/insta-backend